# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'AquaRegistry'
    command: 'login'
  
- bash: |
     docker pull mongo:latest
     docker pull registry.aquasec.com/scanner:latest-saas
  displayName: Download Image for Scanning

- task: aquasecScanner@4
  inputs:
    image: 'mongo:latest'
    scanType: 'local'
    containerRuntime: 'docker'
    register: true
    hideBase: false
    showNegligible: false
    scanner: 'registry.aquasec.com/scanner:latest-saas'
    registry: 'Docker Hub'
    connection: 'AquaImageScanningConnection'