# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'AquaRegistry'
    command: 'login'
  
- bash: |
     docker pull mongo:latest
  #  docker pull registry.aquasec.com/scanner:latest-saas
  #  docker run -v /var/run/docker.sock:/var/run/docker.sock registry.aquasec.com/scanner:latest-saas scan -H https://99c607c318.cloud.aquasec.com -A bc8830944ba2567c10fae95c3bbe432880d262ae0199e2adb571a41b9202cbd4 --local nginx:stable-alpine 
  displayName: Image Scan > Install

- task: AquasecScanner@4
  inputs:
    image: 'mongo:latest'
    scanType: 'local'
    containerRuntime: 'docker'
    register: false
    hideBase: false
    showNegligible: false
    scanner: 'registry.aquasec.com/scanner:latest-saas'
    connection: 'AquaImageScanningConnection'